[{'comment': 'CAN YOU CLAIM ALL THE FARMS?',
  'news': {'attack_mc': {'currentLabel': 'none'},
           'connected_mc': {'currentLabel': 'show'},
           'critical_mc': {'currentLabel': 'show'},
           'dead_mc': {'currentLabel': 'show'},
           'decoration_mc': {'currentLabel': 'show'},
           'defend_mc': {'currentLabel': 'none'},
           'extra_stone_mc': {'currentLabel': 'none'},
           'game_over_mc': {'_5_5_mc': {'confirm_mc': {'dispatchEvent': 'mouseDown'}},
                            'currentLabel': 'preview',
                            'extra_stone_available_mc': {'currentLabel': '_0'},
                            'hide_available_mc': {'currentLabel': '_0'},
                            'mission_mc': {'currentLabel': 'score_5_5_3'},
                            'white_computer_mc': {'currentLabel': 'computer'}},
           'hide_mc': {'currentLabel': 'none'},
           'option_mc': {'block_mc': {'currentLabel': 'show'},
                         'computer_pass_mc': {'currentLabel': 'show'},
                         'empty_block_mc': {'currentLabel': 'show'},
                         'first_capture_mc': {'currentLabel': 'none'},
                         'gibs_mc': {'currentLabel': 'show'},
                         'prohibit_danger_mc': {'currentLabel': 'show'},
                         'score_mc': {'currentLabel': 'show'}},
           'profit_mc': {'currentLabel': 'show'},
           'strike_mc': {'currentLabel': 'show'},
           'suicide_mc': {'currentLabel': 'none'},
           'territory_mc': {'currentLabel': 'show'},
           'top_move_mc': {'currentLabel': 'show'},
           'unconditional_status_mc': {'currentLabel': 'none'}},
  'size': 5},
 {'black': (2, 2),
  'news': {'_0_0_mc': {},
           '_0_1_mc': {},
           '_0_2_mc': {},
           '_0_3_mc': {},
           '_0_4_mc': {},
           '_1_0_mc': {},
           '_1_1_mc': {},
           '_1_2_mc': {},
           '_1_3_mc': {},
           '_1_4_mc': {},
           '_2_0_mc': {},
           '_2_1_mc': {},
           '_2_2_mc': {'last_move_mc': {'currentLabel': 'black'}},
           '_2_3_mc': {},
           '_2_4_mc': {},
           '_3_0_mc': {},
           '_3_1_mc': {},
           '_3_2_mc': {},
           '_3_3_mc': {},
           '_3_4_mc': {},
           '_4_0_mc': {},
           '_4_1_mc': {},
           '_4_2_mc': {},
           '_4_3_mc': {},
           '_4_4_mc': {},
           'comment_mc': {'_txt': {'text': 'PERFECT!  THE CENTER CLAIMS FOUR SIDES.'},
                          'currentLabel': 'comment'},
           'cursor_mc': {'act_mc': {'currentLabel': 'none'},
                         'currentLabel': 'none'},
           'score_mc': {'bar_mc': {'currentLabel': '_24',
                                   'marker_mc': {'change_txt': {'text': '+24'},
                                                 'currentLabel': 'positive'},
                                   'territory_txt': {'text': '24'}}},
           'turn_mc': {'currentLabel': 'white'},
           'turn_veil_mc': {'currentLabel': 'other'}},
  'note': {'_0_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_4_mc': {'decoration_mc': {'currentLabel': 'none'}}}},
 {'news': {'_0_0_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_1_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_2_mc': {'empty_block_south_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'white'}},
           '_0_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_1_0_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_1_1_mc': {'empty_block_east_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'white'}},
           '_1_2_mc': {'block_south_mc': {'currentLabel': 'white_block'},
                       'currentLabel': 'white',
                       'empty_block_south_mc': {'currentLabel': 'block'},
                       'last_move_mc': {'currentLabel': 'white'},
                       'territory_mc': {'currentLabel': 'neutral'}},
           '_1_2_strike_mc': {'south_mc': {'currentLabel': 'white_notice_retaliate'}},
           '_1_3_mc': {'empty_block_west_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'white'}},
           '_1_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_2_0_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_2_1_mc': {'empty_block_east_mc': {'currentLabel': 'you'},
                       'territory_mc': {'currentLabel': 'neutral'},
                       'top_move_mc': {'currentLabel': 'white'}},
           '_2_2_mc': {'block_north_mc': {'currentLabel': 'black_block'},
                       'empty_block_north_mc': {'currentLabel': 'block'}},
           '_2_2_strike_mc': {'north_mc': {'currentLabel': 'black_notice'}},
           '_2_3_mc': {'empty_block_west_mc': {'currentLabel': 'you'},
                       'territory_mc': {'currentLabel': 'neutral'}},
           '_2_4_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_3_0_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_3_1_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_3_2_mc': {'empty_block_north_mc': {'currentLabel': 'you'},
                       'territory_mc': {'currentLabel': 'neutral'},
                       'top_move_mc': {'currentLabel': 'none'}},
           '_3_3_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_3_4_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_4_0_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_4_1_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_4_2_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_4_3_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           '_4_4_mc': {'territory_mc': {'currentLabel': 'neutral'}},
           'cursor_mc': {'act_mc': {'currentLabel': 'play'},
                         'currentLabel': 'black'},
           'score_mc': {'bar_mc': {'currentLabel': '_-9',
                                   'marker_mc': {'change_txt': {'text': '-33'},
                                                 'currentLabel': 'negative'},
                                   'territory_txt': {'text': '-9'}}},
           'turn_mc': {'currentLabel': 'black'},
           'turn_veil_mc': {'currentLabel': 'you'}},
  'note': {'_0_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_4_mc': {'decoration_mc': {'currentLabel': 'none'}}},
  'white': (1, 2)},
 {'black': (1, 1),
  'news': {'_0_0_mc': {},
           '_0_1_mc': {},
           '_0_2_mc': {},
           '_0_3_mc': {},
           '_0_4_mc': {},
           '_1_0_mc': {},
           '_1_1_mc': {'last_move_mc': {'currentLabel': 'black'}},
           '_1_1_strike_mc': {},
           '_1_2_mc': {},
           '_1_2_strike_mc': {},
           '_1_3_mc': {},
           '_1_4_mc': {},
           '_2_0_mc': {},
           '_2_1_mc': {},
           '_2_2_mc': {'last_move_mc': {'currentLabel': 'none'}},
           '_2_2_strike_mc': {},
           '_2_3_mc': {},
           '_2_4_mc': {},
           '_3_0_mc': {},
           '_3_1_mc': {},
           '_3_2_mc': {},
           '_3_3_mc': {},
           '_3_4_mc': {},
           '_4_0_mc': {},
           '_4_1_mc': {},
           '_4_2_mc': {},
           '_4_3_mc': {},
           '_4_4_mc': {},
           'comment_mc': {'_txt': {'text': 'TWO CASTLES BOLDLY PUSH THE DRAGON TO THE EDGE.'},
                          'currentLabel': 'comment'},
           'cursor_mc': {'act_mc': {'currentLabel': 'none'},
                         'currentLabel': 'none'},
           'score_mc': {'bar_mc': {'currentLabel': '_24',
                                   'marker_mc': {'change_txt': {'text': '+33'},
                                                 'currentLabel': 'positive'},
                                   'territory_txt': {'text': '24'}}},
           'turn_mc': {'currentLabel': 'white'},
           'turn_veil_mc': {'currentLabel': 'other'}},
  'note': {'_0_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_4_mc': {'decoration_mc': {'currentLabel': 'none'}}}},
 {'news': {'_0_0_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_1_mc': {'empty_block_south_mc': {'currentLabel': 'you'},
                       'territory_mc': {'currentLabel': 'white'},
                       'top_move_mc': {'currentLabel': 'white'}},
           '_0_2_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_0_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_1_0_mc': {'empty_block_east_mc': {'currentLabel': 'you'},
                       'territory_mc': {'currentLabel': 'white'}},
           '_1_1_mc': {'block_east_mc': {'currentLabel': 'black_warning'},
                       'block_south_mc': {'currentLabel': 'black_warning'},
                       'dragon_status_mc': {'currentLabel': 'white_attack'},
                       'empty_block_south_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'black_dead'}},
           '_1_1_strike_mc': {'east_mc': {'currentLabel': 'black_warning'},
                              'south_mc': {'currentLabel': 'black_warning'}},
           '_1_2_mc': {'empty_block_west_mc': {'currentLabel': 'block'},
                       'last_move_mc': {'currentLabel': 'none'},
                       'territory_mc': {'currentLabel': 'neutral'}},
           '_1_2_strike_mc': {'south_mc': {'currentLabel': 'none'},
                              'west_mc': {'currentLabel': 'none'}},
           '_1_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_1_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_2_0_mc': {'empty_block_east_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'white'}},
           '_2_1_mc': {'block_east_mc': {'currentLabel': 'white_warning'},
                       'block_north_mc': {'currentLabel': 'white_warning'},
                       'currentLabel': 'white',
                       'empty_block_east_mc': {'currentLabel': 'block'},
                       'empty_block_north_mc': {'currentLabel': 'block'},
                       'last_move_mc': {'currentLabel': 'white'},
                       'territory_mc': {'currentLabel': 'neutral'},
                       'top_move_mc': {'currentLabel': 'none'}},
           '_2_1_strike_mc': {'east_mc': {'currentLabel': 'white_warning_retaliate'},
                              'north_mc': {'currentLabel': 'white_warning_retaliate'}},
           '_2_2_mc': {'block_north_mc': {'currentLabel': 'black_warning'},
                       'block_west_mc': {'currentLabel': 'black_warning'},
                       'dragon_status_mc': {'currentLabel': 'white_attack'},
                       'empty_block_west_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'black_dead'}},
           '_2_2_strike_mc': {'north_mc': {'currentLabel': 'black_warning'},
                              'west_mc': {'currentLabel': 'black_warning'}},
           '_2_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_2_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_3_0_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_3_1_mc': {'empty_block_north_mc': {'currentLabel': 'block'},
                       'territory_mc': {'currentLabel': 'white'},
                       'top_move_mc': {'currentLabel': 'black'}},
           '_3_2_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_3_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_3_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_4_0_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_4_1_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_4_2_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_4_3_mc': {'territory_mc': {'currentLabel': 'white'}},
           '_4_4_mc': {'territory_mc': {'currentLabel': 'white'}},
           'cursor_mc': {'act_mc': {'currentLabel': 'play'},
                         'currentLabel': 'black'},
           'score_mc': {'bar_mc': {'currentLabel': '_-25',
                                   'marker_mc': {'change_txt': {'text': '-49'},
                                                 'currentLabel': 'negative'},
                                   'territory_txt': {'text': '-25'}}},
           'turn_mc': {'currentLabel': 'black'},
           'turn_veil_mc': {'currentLabel': 'you'}},
  'note': {'_0_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_0_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_1_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_2_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_3_4_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_0_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_1_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_2_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_3_mc': {'decoration_mc': {'currentLabel': 'none'}},
           '_4_4_mc': {'decoration_mc': {'currentLabel': 'none'}}},
  'white': (2, 1)}]

