[{'add_black': [(1, 0), (2, 1), (2, 2), (2, 3)],
  'add_white': [(3, 0), (3, 1), (3, 2), (3, 3), (3, 4)],
  'comment': "CAN YOU FINISH OUR FARM'S WALL?",
  'news': {'attack_mc': {'currentLabel': 'none'},
           'connected_mc': {'currentLabel': 'show'},
           'critical_mc': {'currentLabel': 'show'},
           'dead_mc': {'currentLabel': 'show'},
           'decoration_mc': {'currentLabel': 'none'},
           'defend_mc': {'currentLabel': 'none'},
           'extra_stone_mc': {'currentLabel': 'none'},
           'game_over_mc': {'_5_5_mc': {'confirm_mc': {'dispatchEvent': 'mouseDown'}},
                            'currentLabel': 'preview',
                            'extra_stone_available_mc': {'currentLabel': '_1'},
                            'hide_available_mc': {'currentLabel': '_0'},
                            'mission_mc': {'currentLabel': 'score_rule'},
                            'white_computer_mc': {'currentLabel': 'computer'}},
           'hide_mc': {'currentLabel': 'none'},
           'option_mc': {'block_mc': {'currentLabel': 'show'},
                         'computer_pass_mc': {'currentLabel': 'show'},
                         'empty_block_mc': {'currentLabel': 'show'},
                         'first_capture_mc': {'currentLabel': 'none'},
                         'gibs_mc': {'currentLabel': 'show'},
                         'prohibit_danger_mc': {'currentLabel': 'show'},
                         'score_mc': {'currentLabel': 'show'}},
           'profit_mc': {'currentLabel': 'none'},
           'strike_mc': {'currentLabel': 'show'},
           'suicide_mc': {'currentLabel': 'none'},
           'territory_mc': {'currentLabel': 'show'},
           'top_move_mc': {'currentLabel': 'show'},
           'tutor_mc': {'currentLabel': 'score'},
           'unconditional_status_mc': {'currentLabel': 'none'}},
  'play': 'black',
  'size': 5}]

