{'level_mc': {'_txt': {'text': '6'},
              'currentLabel': 'up',
              'progress_mc': {'currentLabel': '_10'}},
 'lobby_mc': {'_00_mc': {'capture_3_3_1_mc': {'score_txt': {'text': '$3'}},
                         'capture_3_3_mc': {'score_txt': {'text': '$3'}},
                         'capture_block_easy_mc': {'score_txt': {'text': '$4'}},
                         'capture_block_mc': {'score_txt': {'text': '$2'}},
                         'capture_corner_mc': {'score_txt': {'text': '$6'}},
                         'capture_critical_mc': {'score_txt': {'text': '$1'}},
                         'capture_rule_beside_mc': {'score_txt': {'text': '$1'}}}}}