{'attack_mc': {'currentLabel': 'show'},
 'connected_mc': {'currentLabel': 'show'},
 'critical_mc': {'currentLabel': 'show'},
 'currentLabel': 'table',
 'cursor_mc': {'act_mc': {'currentLabel': 'play'}, 'currentLabel': 'black'},

 'dead_mc': {'currentLabel': 'show'},
 'decoration_mc': {'currentLabel': 'show'},
 'defend_mc': {'currentLabel': 'show'},
 'extra_stone_mc': {'currentLabel': 'gift'},
 'game_over_mc': {'currentLabel': 'none',
                  'start_mc': {'currentLabel': 'enter'}},
 'gateway_mc': {'currentLabel': 'none'},
 'hide_mc': {'currentLabel': 'gift'},
 'liberty_mc': {'currentLabel': 'warn'},
 'lobby_mc': {'join_mc': {'currentLabel': 'join',
                          'join_txt': {'text': 'ethan_start'}}},
 'profit_mc': {'currentLabel': 'show'},
 'strike_mc': {'currentLabel': 'show'},
 'territory_mc': {'currentLabel': 'show'},
 'top_move_mc': {'currentLabel': 'show'},
 'turn_mc': {'black_user_txt': {'text': 'joris_start'},
             'currentLabel': 'black',
             'white_user_txt': {'text': 'ethan_start'}},
 'turn_veil_mc': {'currentLabel': 'you'},
 'unconditional_status_mc': {'currentLabel': 'show'}}

